import { finalText } from "./chatState";
import type { ChatMessage, TableResult } from "./types";

const FORMULA_START = /^[=+\-@\t\r]/;

function csvCell(value: unknown): string {
  let text = value === null || value === undefined ? "" : String(value);
  if (typeof value === "string" && FORMULA_START.test(text)) text = `'${text}`;
  return /[",\n\r]/.test(text) ? `"${text.replace(/"/g, '""')}"` : text;
}

export function tableToCsv(table: TableResult): string {
  const lines = [table.columns.map(csvCell).join(",")];
  table.rows.forEach((row) => lines.push(row.map(csvCell).join(",")));
  return lines.join("\n") + "\n";
}

export function downloadText(filename: string, text: string, mime: string): void {
  const url = URL.createObjectURL(new Blob([text], { type: mime }));
  const link = document.createElement("a");
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  link.remove();
  URL.revokeObjectURL(url);
}

function markdownTable(table: TableResult, limit = 20): string {
  const head = `| ${table.columns.join(" | ")} |\n| ${table.columns.map(() => "---").join(" | ")} |`;
  const rows = table.rows.slice(0, limit).map((row) => `| ${row.map((cell) => String(cell ?? "").replace(/\|/g, "/")).join(" | ")} |`);
  const more = table.rows.length > limit ? `\n\n_${table.rows.length - limit} more rows not shown._` : "";
  return [head, ...rows].join("\n") + more;
}

export function buildReport(messages: ChatMessage[], title: string): string {
  const parts = [`# ${title}`, `_Generated by DataPilot on ${new Date().toISOString().slice(0, 10)}_`];
  messages.forEach((message) => {
    if (message.role === "user") {
      parts.push(`## ${message.text}`);
      return;
    }
    const answer = finalText(message);
    if (answer) parts.push(answer);
    message.steps.forEach((step) => {
      if (step.kind !== "tool" || !step.result?.ok) return;
      const result = step.result;
      if (result.chart) {
        parts.push(`**Chart: ${result.chart.title}**\n\n${markdownTable({ columns: Object.keys(result.chart.data[0] ?? {}), rows: result.chart.data.map((d) => Object.values(d)), row_count: result.chart.data.length, truncated: false })}`);
      } else if (result.table) {
        parts.push(markdownTable(result.table));
      }
      result.anomalies.forEach((a) => parts.push(`**Anomaly check on ${a.column} (${a.method}, ${a.severity}):** ${a.reason}`));
      if (result.sql) parts.push("```sql\n" + result.sql + "\n```");
      if (result.code) parts.push("```python\n" + result.code + "\n```");
    });
    message.warnings.forEach((w) => parts.push(`> ${w}`));
  });
  return parts.join("\n\n") + "\n";
}
